"use client";

import localFont from "next/font/local";
import "./globals.css";
import { AntDesignConfigProvider } from "@spifa/ui/app";
import { ReactNode } from "react";
import { SessionProvider } from "next-auth/react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

// export const metadata: Metadata = {
//   title: "СПИФА",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  // const session = useSession();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={"container"}>
          <SessionProvider>
            <AntDesignConfigProvider>{children}</AntDesignConfigProvider>
          </SessionProvider>
        </div>
      </body>
    </html>
  );
}
