import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AntDesignConfigProvider } from "@spifa/ui/shared/config/AntDesignConfigProvider";
import { ReactNode } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "СПИФА",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div>
          <AntDesignConfigProvider>{children}</AntDesignConfigProvider>
        </div>
      </body>
    </html>
  );
}
