import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AntDesignConfigProvider } from "@spifa/ui/app";
import { ReactNode } from "react";
import { auth } from "../auth";
import { SessionProvider } from "next-auth/react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "СПИФА",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={"container"}>
          <SessionProvider session={session}>
            <AntDesignConfigProvider>{children}</AntDesignConfigProvider>
          </SessionProvider>
        </div>
      </body>
    </html>
  );
}
